stages:
    - test

.composer_cache: &composer_cache
    cache:
        paths:
            - vendor/

.install_dependencies: &install_dependencies
    before_script:
        - curl -sS https://getcomposer.org/installer | php
        - php composer.phar install --prefer-dist --classmap-authoritative --no-interaction --no-progress

.composer_test: &composer_test
    script:
        - php composer.phar test

php 7.0:
    image: php:7.0-alpine
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache

php 7.1:
    image: php:7.1-alpine
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache

php 7.2:
    image: php:7.2-rc-alpine
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache
