stages:
    - mirror
    - test

.composer_cache: &composer_cache
    cache:
        paths:
            - vendor/

.install_dependencies: &install_dependencies
    before_script:
        - apk add --update --no-cache autoconf coreutils autoconf gcc g++ make
        - pecl install xdebug
        - docker-php-ext-enable xdebug
        - curl -sS https://getcomposer.org/installer | php
        - php composer.phar install --prefer-dist --classmap-authoritative --no-interaction --no-progress

.composer_test: &composer_test
    script:
        - php composer.phar test

.code_coverage: &code_coverage
    after_script:
        - bash <(curl -s https://codecov.io/bash)

github:
    before_script:
        - apk add --update --no-cache bash git openssh
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
        - ssh-keyscan github.com | sort -u - ~/.ssh/known_hosts -o ~/.ssh/known_hosts
        - bash -c "ssh-add <(echo '$SSH_GITHUB_GITLAB')"

    image: alpine:latest
    stage: mirror
    script:
        - git push --mirror git@github.com:ThePixelDeveloper/Sitemap.git

php 7.0:
    image: php:7.0-alpine
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache
    <<: *code_coverage

php 7.1:
    image: php:7.1-alpine
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache
    <<: *code_coverage

php 7.2:
    image: php:7.2-rc-alpine
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache
    <<: *code_coverage
