stages:
    - test

.composer_cache: &composer_cache
    cache:
        paths:
            - vendor/

.install_dependencies: &install_dependencies
    before_script:
        - composer install --prefer-dist --classmap-authoritative --no-interaction --no-progress

.composer_test: &composer_test
    script:
        - composer test

php 7.0:
    image: www.devkit.net:4567/thepixeldeveloper/docker-images/php-7.0:latest
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache

php 7.1:
    image: www.devkit.net:4567/thepixeldeveloper/docker-images/php-7.1:latest
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache

php 7.2:
    image: www.devkit.net:4567/thepixeldeveloper/docker-images/php-7.2:latest
    stage: test
    <<: *install_dependencies
    <<: *composer_test
    <<: *composer_cache
